/* Task 1 */
DELETE FROM KHACHHANG
WHERE TenKhachHang = 'Le Thi A'

/* Task 2 */
UPDATE KHACHHANG
SET MaKhuVuc = 'KV003'
WHERE MaKhuVuc = 'KV001'

/* Task 3 */
SELECT TenThanhVienGiaoHang
FROM THANHVIENGIAOHANG
WHERE TenThanhVienGiaoHang LIKE 'Tr%' AND
LEN(TenThanhVienGiaoHang)>=25

/* Task 4 */
SELECT DONHANG_GIAOHANG.*
FROM DONHANG_GIAOHANG INNER JOIN KHUVUC ON
DONHANG_GIAOHANG.MaKhuVucGiaoHang = KHUVUC.MaKhuVuc
WHERE NgayGiaoHang LIKE '%2017' AND TenKhuVuc='Hai Chau'

/* Task 5 */
SELECT MaDonHangGiaoHang, THANHVIENGIAOHANG.MaThanhVienGiaoHang,
TenThanhVienGiaoHang, NgayGiaoHang, PhuongThucThanhToan
FROM DONHANG_GIAOHANG INNER JOIN THANHVIENGIAOHANG
ON DONHANG_GIAOHANG.MaThanhVienGiaoHang =
THANHVIENGIAOHANG.MaThanhVienGiaoHang
WHERE TrangThaiGiaoHang ='Da giao hang'
ORDER BY NgayGiaoHang, PhuongThucThanhToan DESC

/* Task 6 */
SELECT THANHVIENGIAOHANG.*
FROM THANHVIENGIAOHANG
WHERE GioiTinh='Nam' AND MaThanhVienGiaoHang NOT IN (SELECT
MaThanhVienGiaoHang FROM DONHANG_GIAOHANG)

/* Task 7 */
SELECT DISTINCT(TenKhachHang)
FROM KHACHHANG

SELECT TenKhachHang
FROM KHACHHANG
GROUP BY TenKhachHang

/* Task 8 */
SELECT KHACHHANG.MaKhachHang, TenKhachHang,
DiaChiNhanHang, MaDonHangGiaoHang,
PhuongThucThanhToan, TrangThaiGiaoHang
FROM KHACHHANG LEFT JOIN DONHANG_GIAOHANG
ON KHACHHANG.MaKhachHang = DONHANG_GIAOHANG.MaKhachHang

/* Task 9 */
SELECT THANHVIENGIAOHANG.MaThanhVienGiaoHang
FROM THANHVIENGIAOHANG INNER JOIN DONHANG_GIAOHANG
ON THANHVIENGIAOHANG.MaThanhVienGiaoHang =
DONHANG_GIAOHANG.MaThanhVienGiaoHang
INNER JOIN KHUVUC ON DONHANG_GIAOHANG.MaKhuVucGiaoHang = KHUVUC.MaKhuVuc
WHERE GioiTinh='Nu' AND TenKhuVuc='Hai Chau'
GROUP BY THANHVIENGIAOHANG.MaThanhVienGiaoHang
HAVING COUNT(DONHANG_GIAOHANG.MaKhachHang)=10

/* Task 10 */
SELECT KHACHHANG.*
FROM KHACHHANG INNER JOIN DONHANG_GIAOHANG
ON KHACHHANG.MaKhachHang = DONHANG_GIAOHANG.MaKhachHang
INNER JOIN KHUVUC ON DONHANG_GIAOHANG.MaKhuVucGiaoHang = KHUVUC.MaKhuVuc
WHERE TenKhuVuc='Lien Chieu'
EXCEPT
SELECT KHACHHANG.*
FROM KHACHHANG INNER JOIN DONHANG_GIAOHANG
ON KHACHHANG.MaKhachHang = DONHANG_GIAOHANG.MaKhachHang
INNER JOIN THANHVIENGIAOHANG 
ON DONHANG_GIAOHANG.MaThanhVienGiaoHang=THANHVIENGIAOHANG.MaThanhVienGiaoHang
WHERE GioiTinh='Nam'
